server:
  port: 8884
  address: 0.0.0.0
  servlet:
    context-path: /test-service

spring:
    application:
      name:
eureka:
 client:
     serviceUrl:
       defaultZone:  http://eureka.didispace.com/eureka/
 instance:
   prefer-ip-address: true

test-service :
   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule

logging:
            level:
                root: info
                org.dromara.soul : debug
            path: "./logs"

